#!/usr/bin/env python

import argparse
import os
import subprocess

parser = argparse.ArgumentParser(
  description="manage butti and its services"
)

parser.add_argument(
    'command', action="store",
    choices=["link", "start", "stop", "status", "update"]
)

args = parser.parse_args()


def link_command():
    src = os.path.abspath('./butti')
    dst = '/usr/bin/butti'
    os.symlink(src, dst)
    print "Symlink created successfully. You can now run `butti` " + \
          "command to manage butti and its services"


def start_butti():
    compose_file = os.path.join(
        os.path.dirname(os.path.realpath(__file__)),
        "docker-compose.yml"
    )
    cmd = ["docker-compose", "-f", compose_file, "up", "-d"]
    subprocess.call(cmd)
    print "butti started"


def stop_butti():
    compose_file = os.path.join(
        os.path.dirname(os.path.realpath(__file__)),
        "docker-compose.yml"
    )
    cmd = ["docker-compose", "-f", compose_file, "down"]
    subprocess.call(cmd)
    print "butti stopped"


def butti_status():
    cmd = ["docker", "ps", "-a"]
    subprocess.call(cmd)


def update():
    dir = os.path.dirname(os.path.realpath(__file__))
    os.chdir(dir)
    cmd = ["git", "pull"]
    subprocess.call(cmd)


if __name__ == "__main__":
    if args.command == "link":
        link_command()
    elif args.command == "start":
        start_butti()
    elif args.command == "stop":
        stop_butti()
    elif args.command == "status":
        butti_status()
    elif args.command == "update":
        update()
    else:
        print "Nothing to do"
